version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly
  go: "1.25"

linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - unused
    - ineffassign
    - gocritic
    - revive
    - exhaustive
    - gosec
    - prealloc
    - misspell
    - nolintlint

formatters:
  enable:
    - gofumpt

linters-settings:
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance

  gofumpt:
    extra-rules: true

  revive:
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: exported
      - name: increment-decrement
      - name: var-naming
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: errorf
      - name: empty-block
      - name: superfluous-else
      - name: unreachable-code

  exhaustive:
    default-signifies-exhaustive: true

  misspell:
    locale: US

issues:
  exclude-dirs:
    - vendor
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
